### PR TITLE
Merge https://github.com/JakubVanek/openbve to this repository

### PR DESCRIPTION
**Pull request by JakubVanek**
Hi!
I made some progress to openBVE and it seemed wrong to me that there would be two repositories with some progress. So I think that it would be good to merge my repository into this repository.
End-user visible changes:
- SDL2# & OpenTK as replacement for deprecated Tao
- New security (train plugin) keys (M-Z)
- Uses SDL scancodes instead of SDL keycodes
  - Note: WinForms controls editor now shows both physical and virtual keys.
- Animated loading screen (train/route loading percentage)

API changes:
- Split Interface class to smaller classes:
  - BlackBox - train logs
  - Controls
  - Conversions - the TryParse... functions
  - Debug - program's error log
  - Hud
  - Options - note: CurrentOptions is renamed to Current
  - Strings - Translation engine
- Put all vectors to OpenBveApi
  - Double- and Single- precision vectors are provided by default
- Joystick class now provides a SDL Guid.

Prebuilt binaries: I built them with Mono 4.0.3, I don't know how much compatible it is with Windows. I cannot enable large address aware mode because I haven't the editbin program.
Sorry if this PR is too much big, I spotted this repository recently.
Jakub Vaněk

### CODE REVIEW

**Comment by JakubVanek** [comment]
wait, it doesn't work on windows...

**Comment by JakubVanek** [comment]
wait, it doesn't work on windows...

**Comment by JakubVanek** [comment]
seems it works now

**Comment by JakubVanek** [comment]
I created now windows build with large address aware enabled.

**Comment by shadow93** [comment]
Thank you!

**Pull request merged**
